version: '2'
services:
    jhipsterangular4-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jhipsterangular4/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterangular4
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
